=== Creature121/RestaurantWebsite/menu/menu.dtd
<!ELEMENT Menu (MenuItem)*>
  <!ELEMENT MenuItem (category|image|description|price)*>
  <!ELEMENT category (#PCDATA)>
  <!ELEMENT image (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT price (regular|full|half)*>
  <!ELEMENT regular (#PCDATA)>
  <!ELEMENT full (#PCDATA)>
  <!ELEMENT half (#PCDATA)>

=== Creature121/RestaurantWebsite/menu/menu.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="menu.xsl" ?>
<!DOCTYPE Menu SYSTEM "menu.dtd">
<Menu>
  <!-- Chicken Sandwich -->
  <MenuItem category="Sandwiches">
    <image>../img/ChickSand.webp</image>
    <description>
      Chicken Sandwich
    </description>
    <price>
      <regular>
        $4
      </regular>
    </price>
  </MenuItem>

  <!-- Roasted Beef -->
  <MenuItem category="Sandwiches">
    <image>../img/RoastBeef.webp</image>
    <description>
      Roasted Beef
    </description>
    <price>
      <regular>
        $10
      </regular>
    </price>
  </MenuItem>

  <!-- Ham Sandwich -->
  <MenuItem category="Sandwiches">
    <image>../img/HamSand.webp</image>
    <description>
      Ham Sandwich
    </description>
    <price>
      <regular>
        $8
      </regular>
    </price>
  </MenuItem>

  <!-- Roasted Turkey -->
  <MenuItem category="Main Course">
    <image>../img/RoastedTurkey.webp</image>
    <description>
      Roasted Turkey
    </description>
    <price>
      <full>
        $24
      </full>
      <half>
        $18
      </half>
    </price>
  </MenuItem>

  <!-- Honey Roast Ham -->
  <MenuItem category="Main Course">
    <image>../img/HoneyRoastHam.jpg</image>
    <description>
      Honey Roast Ham
    </description>
    <price>
      <full>
        $53
      </full>
      <half>
        $26
      </half>
    </price>
  </MenuItem>

  <!-- Mac and Cheese -->
  <MenuItem category="Main Course">
    <image>../img/MacCheese.webp</image>
    <description>
      Mac &amp; Cheese
    </description>
    <price>
      <regular>
        $16
      </regular>
    </price>
  </MenuItem>

  <!-- Chicken Marbella -->
  <MenuItem category="Main Course">
    <image>../img/ChickMarb.webp</image>
    <description>
      Chicken Marbella
    </description>
    <price>
      <regular>
        $36
      </regular>
    </price>
  </MenuItem>

  <!-- Chocolate Milkshake -->
  <MenuItem category="Milkshakes">
    <image>../img/ChocMilk.webp</image>
    <description>
      Chocolate Milkshake
    </description>
    <price>
      <regular>
        $4
      </regular>
    </price>
  </MenuItem>

  <!-- Vanilla Milkshake -->
  <MenuItem category="Milkshakes">
    <image>../img/VanMilk.webp</image>
    <description>
      Vanilla Milkshake
    </description>
    <price>
      <regular>
        $5
      </regular>
    </price>
  </MenuItem>

  <!-- Strawberry Milkshake -->
  <MenuItem category="Milkshakes">
    <image>../img/StrawMilk.webp</image>
    <description>
      Strawberry Milkshake
    </description>
    <price>
      <regular>
        $5
      </regular>
    </price>
  </MenuItem>

  <!-- Pomegranate Juice -->
  <MenuItem category="Beverages">
    <image>../img/PomJuice.webp</image>
    <description>
      Pomegranate Juice
    </description>
    <price>
      <regular>
        $4
      </regular>
    </price>
  </MenuItem>

  <!-- Apple Cider -->
  <MenuItem category="Beverages">
    <image>../img/AppCId.webp</image>
    <description>
      Apple Cider
    </description>
    <price>
      <regular>
        $5
      </regular>
    </price>
  </MenuItem>

  <!-- Soft Drinks -->
  <MenuItem category="Beverages">
    <image>../img/Soft.webp</image>
    <description>
      Soft Drinks
    </description>
    <price>
      <regular>
        $4
      </regular>
    </price>
  </MenuItem>

  <!-- Water -->
  <MenuItem category="Beverages">
    <image>../img/Water.webp</image>
    <description>
      Water
    </description>
    <price>
      <regular>
        $3
      </regular>
    </price>
  </MenuItem>
</Menu>
